#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 Citadel and contributors
#
# SPDX-License-Identifier: MIT

CITADEL_ROOT="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/../..)"

signal="${1}"
command=${signal%%"-"*}
app=${signal#*"-"}

"${CITADEL_ROOT}/app/app-manager.py" "${command}" "${app}"
